// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDldMHXR5F4EJXqTbAAwlORi2oNmBZc8bM',
    appId: '1:961590488389:web:7f88ce168677cc40b8e22c',
    messagingSenderId: '961590488389',
    projectId: 'texter-4bfcf',
    authDomain: 'texter-4bfcf.firebaseapp.com',
    storageBucket: 'texter-4bfcf.appspot.com',
    measurementId: 'G-FQ5JKCDFHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpbF-xqQqHSsxaRNyzv0Zb2O-JiF4wpog',
    appId: '1:961590488389:android:1fe0d7fec8d2ac0db8e22c',
    messagingSenderId: '961590488389',
    projectId: 'texter-4bfcf',
    storageBucket: 'texter-4bfcf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS49qBOQxgz6gvHt0gicF9wsu5xMebOm0',
    appId: '1:961590488389:ios:c722fc3bb05092bbb8e22c',
    messagingSenderId: '961590488389',
    projectId: 'texter-4bfcf',
    storageBucket: 'texter-4bfcf.appspot.com',
    iosBundleId: 'com.example.texter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS49qBOQxgz6gvHt0gicF9wsu5xMebOm0',
    appId: '1:961590488389:ios:8e65cbcf0593f5e1b8e22c',
    messagingSenderId: '961590488389',
    projectId: 'texter-4bfcf',
    storageBucket: 'texter-4bfcf.appspot.com',
    iosBundleId: 'com.example.texter.RunnerTests',
  );
}
